CREATE TABLE COUNTRY (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        NAME VARCHAR(50)
    );
ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PRIMARY_KEY PRIMARY KEY (ID);
CREATE UNIQUE INDEX COUNTRY_NAME_IDX ON COUNTRY(NAME);
 
CREATE TABLE CITY (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        COUNTRY_ID INTEGER NOT NULL,
        NAME VARCHAR(50)
    );
ALTER TABLE CITY ADD CONSTRAINT CITY_PRIMARY_KEY PRIMARY KEY (ID); 
ALTER TABLE CITY ADD CONSTRAINT CITY_FOREIGNKEY_COUNTRY_ID FOREIGN KEY (COUNTRY_ID)
    REFERENCES COUNTRY (ID);
CREATE UNIQUE INDEX CITY_NAME_IDX ON CITY(NAME);
 
--
-- Initialize with some values
--
INSERT INTO COUNTRY (NAME) VALUES ('Austria');
INSERT INTO COUNTRY (NAME) VALUES ('Italy');
INSERT INTO COUNTRY (NAME) VALUES ('USA');
 
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'Austria'), 'Graz');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'Austria'), 'Linz');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'Austria'), 'Salzburg');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'Austria'), 'Wien');
 
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'Italy'), 'Bologna');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'Italy'), 'Firenze');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'Italy'), 'Roma');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'Italy'), 'Venezia');
 
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'USA'), 'Atlanta');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'USA'), 'Los Angeles');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'USA'), 'New York');
INSERT INTO CITY (COUNTRY_ID, NAME)
    VALUES ((SELECT ID FROM COUNTRY WHERE NAME = 'USA'), 'Washington');